version: "3.8"
services:
  school-registration-system-app:
    build: .
    image: school-registration-system
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=docker
    depends_on:
      - mysqldb
  #    restart: on-failure

  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=school-registration-system-db
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

volumes:
  db: