version: "3"
services:
  school-registration-system-app:
    image: school-registration-system
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/school-registration-system-db?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_DATABASE=school-registration-system-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass123
      - MYSQL_ROOT_PASSWORD=pass123

networks:
  springmysql-net: